### ISSUE TITLE
Prerequisites need to be documented

### ISSUE THREAD

**Issue by PabluskiNC** [MicroPyramid/MicroSite#277]
Thank you for sharing your work. I appreciate being able to learn by seeing how others do things.

I have been able to get MicroSite running in an Ubuntu 16, Python 3.5.2, dJango 1.9.7 environment, but only after much struggle.

Please include an install guide and a list of non-python pre-reqs.

These are some of the issues I had to resolve before the site would work ...

- install libxml-2-dev, libxslt-dev
- install postgres
      - set postgres user p/w to "root" or change in settings.py
      - create the database and tablespace needed
- install elasticsearch
     - make sure to enable daemon mode in /etc/default/elasticsearch
     - make sure that it is using ipv4 for the 9200 & 9300 ports
- install lessc (or disable it by setting "COMPRESS_ENABLED = False" and "COMPRESS_PRECOMPILERS = []" in settings.py)

**Comment by ashwin31** [comment]
@PabluskiNC please check docs and its updated there.
